### PR TITLE
Add Default instances for Control.Applicative

### PR DESCRIPTION
**Pull request by ryantrinkle**
Includes two functors:
- Const
- ZipList

### CODE REVIEW

**Comment by ryantrinkle** [comment]
@mauke Any thoughts on this?

**Comment by ryantrinkle** [comment]
@mauke Is there anything I can do to help move this along?

**Comment by mauke** [comment]
I'm not sure the default for ZipList is correct. Why isn't it
```haskell
def = ZipList (repeat def)
```
?

**Comment by mauke** [comment]
The `Const` instance exists now. As for `ZipList`, I'm going to close this for now until I see a better argument for which instance we want: 0, 1, or many (i.e. `ZipList []`, `ZipList [def]`, or `ZipList (repeat def)`).

**Pull request closed without merging**
