### PR TITLE
Adding the DefaultM monadic interface.

### PR DESCRIPTION
**Pull request by wdanilo**

### CODE REVIEW

**Comment by fizruk** [comment]
Why would you need this specific class?
Perhaps an explicit use case might be of help here.

This particular interface can be replaced easily with a `newtype`:

```haskell
newtype DefaultM m a = DefaultM { getDefaultM :: m a }

instance (Monad m, Default a) => Default (DefaultM m a) where
  def = DefaultM (return def)
```

BTW, in presence of [AMP](https://wiki.haskell.org/Functor-Applicative-Monad_Proposal) we can replace `Monad` with `Applicative` and `return` with `pure`.

**Comment by mauke** [comment]
I don't see how this is useful, and overlapping instances scare me.

**Comment by wdanilo** [comment]
Oh, I think we can discuss it further here. Imagine a record, which has "default" instance, but its default instance can be constructed only when it has access to some monadic stack (it wants for example access `GraphBuilder` if it is a `Node`). Then we can just use `defaultM` here. @mauke why it scares you? I didn't expected such answer to be honest because `OverlappingInstances` are rather widely used ...

**Comment by wdanilo** [comment]
In new GHC we can of course use the instance-specific `{-# OVERLAPPABLE #-}` pragma, which will affect ONLY this instance. Even better - in new GHC we don't have to use any pragma, because we can control it in the files when we use it.

**Comment by mauke** [comment]
I still don't see how this is useful. I haven't run into a problem where I would need it, so it's hard for me to judge whether this would be a good thing.

In the meantime, if you need this, can't you release it as a separate module? AFAICS there's no technical need for it to be in `Data.Default` itself.

**Comment by wdanilo** [comment]
@mauke: Of course I can, it just fits perfectly into this module. This is just default instance of a datatype, that can be generated in a monad, that's all. Releasing milions of small modules that provide very similar things for different use cases is a little bit strange, but I can release something like `data-default-plus` (or something with another name) which will reexport things from `data-default` with additional classes.

**Pull request closed without merging**
